### ISSUE TITLE
Issue with component rendering after update

### ISSUE THREAD

**Issue by redhouse1987** [tshaddix/react-chrome-redux#122] opened 2018-01-07 21:10 UTC
I recently updated from v 1.33 to 1.5 and am having an issue with my components rendering. The issue is persistent across both my background and content script. 

In short if I make a change to the state for example on my popup script component I can see in the background script that the state updates but the component won't actually render the change until I close the popup window and re-open it. Looking through the releases I guess this is coming as a result of the 1.4 release where the proxy store state only receives a diff of the changes. 

Not sure if you might know where the issue might lye or if you've seen someone else encounter the same issue?

Thanks and love the work you guys have done so far on this!

**Comment by tshaddix** [comment] 2018-01-07 23:41
@redhouse1987 Woa well that's not good! Let me try reproducing it on my end.

**Comment by tshaddix** [comment] 2018-01-08 00:00
@redhouse1987 I'm not currently able to produce this with the simple examples we have. Would you be able to provide more context or a simple example of what you are experiencing? Maybe a quick video?

**Comment by vhmth** [comment] 2018-01-08 00:48
If you could provide the sample code, that would also be helpful @redhouse1987

**Comment by redhouse1987** [comment] 2018-01-08 13:47
Thanks for the quick reply fellas, will try and provide some example code soon. In the mean time here's a video of the issue:

https://vimeo.com/250112642

Thanks

**Comment by tshaddix** [comment] 2018-01-08 15:55
@redhouse1987 interesting. Beautiful extension btw :)

One quick thing I'd love to check is to make sure the proxy store is emitting changes via `subscribe()`.

Could you add this to your popup code?

```js
// in your popup.js
// store refers to react-chrome-redux proxy store

store.subscribe(() => {
  console.dir(store.getState());
});
```

I'm interested in:
1. Is the store receiving a state change event from the `event` page?
2. Is this updated state the one you are looking for?

If the answer is yes to both of these, then we can take the hunt to the popup code.

**Comment by redhouse1987** [comment] 2018-01-08 20:10
Thank you! So yes the store is receiving a state change from the event page and it is the correct updated state which should render the other tab view. 

Here is the rest of the code in the popup index.js:

```
import React from 'react';
import {render} from 'react-dom';

import App from './App';

import {Store} from 'react-chrome-redux';
import {Provider} from 'react-redux';

const proxyStore = new Store({
  portName: 'example'
});

proxyStore.ready().then(() => {
render(
    <Provider store={proxyStore}><App /></Provider>
  , document.getElementById('app'));
});
```

**Comment by tshaddix** [comment] 2018-01-09 15:50
@redhouse1987 Well that's super interesting... If that's the case then it sounds like everything is just working fine and dandy in the store logic.  We can confirm this by adding some sort of `componentWillReceiveProps()` call in your `App.jsx` and logging the new props. If the app is receiving those props at the right time with the right values, then this may lay outside of `react-chrome-redux`

**Comment by redhouse1987** [comment] 2018-01-09 22:21
How strange - none of my React life-cycle methods seem to be firing. I tried` componentWillReceiveProps()`, `componentDidMount()` and `componentDidUpdate()` and couldn't even get any text logged in the console. Like you say the store logic appears to be working just fine but i'm a little stumped as to what could be going on with the component rendering. Any ideas @tshaddix?

**Comment by tshaddix** [comment] 2018-01-10 01:43
@redhouse1987 that's really interesting... not sure at all what could be going on. If you have an additional example code we could look at, that might help!

**Comment by vhmth** [comment] 2018-01-15 19:06
@redhouse1987 having a sample code snippet is always really useful within the context of `react-chrome-redux` simply because a lot of issues we get are due to people not understanding the nature of extension development or how this library plays within that environment specifically. It just helps save us some guess work. Even a stripped-down example that you can repro on your computer would be greatly appreciated!

**Comment by redhouse1987** [comment] 2018-01-15 19:53
Hi guys! Sorry for the slow response, I have been busy and not had the time to put an example together. Will try get it together this week.

**Comment by redhouse1987** [comment] 2018-01-15 23:48
Had some time tonight so managed to get an example together @tshaddix @vhmth :

https://github.com/redhouse1987/react-chrome-redux-issue

**Comment by redhouse1987** [comment] 2018-01-23 21:28
Hey @tshaddix @vhmth, have you guys managed to take a look at the issue in the example repo yet?

**Comment by tshaddix** [comment] 2018-01-28 18:09
Hi @redhouse1987 , I've looked through it a couple times trying to find something obvious. Next step for me is to actually try loading it up and see if I can reproduce.

**Comment by ghargrove** [comment] 2018-02-02 16:43
@ericnkatz and I recently attempted to jump from version 1.3.2 and have encountered a similar issue. 

After an action is dispatched the logger shows the redux store in the correct state, but the store object in the content script does not reflect that correct state.

Not sure if it's helpful or not. But a weird thing I noticed is that sometimes some of the data is there and sometimes the data is not. 
Say I had fields for `duck`, 'goose', `eagle`. Sometimes duck and goose are there (usually always together). Sometimes they are not. And eagle is never there.

Will continue to dig around.

**Comment by ghargrove** [comment] 2018-02-02 17:04
Forgot to mention that I tried subscribing to the store as @tshaddix described in the comment above. The listener was triggered but the state was incorrect. 

Oddly when i looked under the `_root.entries` key there appeared to be data in there that did reflect the redux state. Notice the tabs object is empty. But under `_root.entries` there is data.

<img width="1276" alt="screen shot 2018-02-02 at 12 02 20 pm" src="https://user-images.githubusercontent.com/4655909/35745351-fbfaa6d8-0810-11e8-9f0a-c5ce67e064fc.png">

**Comment by ericnkatz** [comment] 2018-02-06 17:05
Is it possible that somewhere the changes in https://github.com/tshaddix/react-chrome-redux/pull/100/files introduced this issue?

**Comment by tshaddix** [comment] 2018-02-14 17:59
@ericnkatz I think that's the most likely case. The diff and patchState is most likely missing something. I'm pretty confident this is a bug now.

**Comment by tshaddix** [comment] 2018-02-14 18:19
Alright, I've started to make some progress. I'm looking at the `shallowDiff` function and seeing the two objects entering it (old state and new state) having the same navigation state:

![screenshot 2018-02-14 at 10 17 10 am](https://user-images.githubusercontent.com/2173532/36220711-7efdb76a-1170-11e8-9bed-9263aef181f4.png)

**Comment by tshaddix** [comment] 2018-02-14 20:25
@redhouse1987 I found the error. In your navigation reducer, you are not returning a new state object, but instead using the existing one and [overwriting the property](https://github.com/redhouse1987/react-chrome-redux-issue/blob/master/background/reducers/navigationReducer.js#L9).

The problem with this is that you are essentially changing the referenced "prevState" object used for patching diffs, so when the patch state starts looking for changes it is actually using the same object. With redux, we should never [mutate the existing state](https://redux.js.org/docs/recipes/UsingObjectSpreadOperator.html).

Your stuff works by changing L9 in your navigation reducer to this:

```js
 case 'SWITCH_LOGIN_REG_TAB': {
      let newNav = action.view;
      const newState = Object.assign({}, state, {
        popupLoginRegVariance:newNav
      });

      return newState;
}					
```

Notice here we are now assigning to a new object, not the existing state.

**Closed by tshaddix** 2018-02-14 20:25 UTC
Labels: bug

**Comment by tshaddix** [comment] 2018-02-14 20:27
@ericnkatz @ghargrove If this isn't the case for your apps, let's open a new issue with your code :)

**Comment by ericnkatz** [comment] 2018-02-14 20:30
Sounds good. Will try to generate a concrete example to reproduce.

**Comment by redhouse1987** [comment] 2018-02-15 13:36
Makes perfect sense and an oversight on my behalf! Thanks for the help @tshaddix

**Comment by tshaddix** [comment] 2018-02-15 19:05
@redhouse1987 no problem!
