### ISSUE TITLE
Objective of this project

### ISSUE THREAD

**Issue by skyiea** [tshaddix/react-chrome-redux#34] opened 2016-10-24 19:17 UTC
Hey guys.
So what is the goal of this project? Given that there is Chrome Storage, which can be used to store data there, what is real benefit of using single Redux Store within background Page in comparison to multiple ones inside Views?
It seems to me that this is somewhat overhead. Why don't just treat each View as separate application with its complete structure?
I'm pretty newbie in extension development world, thus I might be missing something obvious in this regard.

**Comment by tshaddix** [comment] 2016-10-25 02:25
You can read all about why this package was designed the way it was in the [introduction](https://github.com/tshaddix/react-chrome-redux/wiki/Introduction). There is also a bonus [video](https://www.youtube.com/watch?v=k88OIWJENgE) where I introduce the idea.

Long story short: This package treats the background page as the store, and the ui pages as front end components. This allows you to simplify the data structure of your app, and provides a single source of truth for your entire extension. Your background store state represents the entire state of your extension, and that's pretty cool (just like a web app).

I'm not really sure how the chrome.storage API comes into this. Chrome storage is used for persisting data and syncing across devices, while this package and Redux provides an application structure. I use both the storage API (to store the state of the extension) and this package in [my apps](https://github.com/tshaddix/next-read/blob/master/event/src/index.js#L12-L38).

In no way am I claiming that this package solves all problems for all extensions. It might not be right for yours, but it's worked great for ours :)

**Comment by tshaddix** [comment] 2016-10-25 02:26
I'm going to close this for now as I'm not sure I can add anything else to this, but I'm happy to continue the discussion!

**Closed** 2016-10-25 02:26 UTC
Labels: question

**Comment by skyiea** [comment] 2016-10-25 07:18
What I was thinking in regard of Chrome Storage API is that it could to be used (via *onChanged* listener) to sync Store State between each View, thus no need to put this task on background page shoulders. So each View will have complete Redux flow, with its Actions, Reducers and Store (which will be always in sync with Chrome Storage, the same across all Views).

Let's take some example, say we want to change some setting in *Options page* and it should immediately be picked by all Views. 
According to your workflow it will be done in this way (correct me if I'm wrong):
`Options page -> executes Proxy Action -> Message passing to background page -> Update Redux Store [-> async update Chrome Storage state] -> Message passing to all Views with updated Store state -> Proxy Store notifies all subscribed Page Components about change`
How I see it might be done instead:
`Options page -> executes Action -> Update Store [-> async update Chrome Storage state -> Automatically notify all subscribed Views] -> Notify all subscribed Page Components on particular page`

Here you might see that in terms of "what is easier to comprehend" my workflow is just regular Redux with tiny inclusion of syncing with Chrome Storage, while you are using Proxy Actions, Reducers and Store on background page, and all these message passing procedures.
Does it worth to do that just for keeping single Store instance within background page instead of multiple ones always synced?

**Comment by tshaddix** [comment] 2016-10-25 15:08
I'm not trying to sell you on this philosophy.  Please understand that it's hard for me to reply to questions like "is it worth it?".

That's largely a matter of opinion. Is it worth it in terms of developer productivity? Is it worth it in terms of speed? Is it worth it in terms of stability and fault-tolerance? 

This package has connected with quite a few people because it allows them to treat their Chrome Extension like a simplified web-app. Feel free to not use this if that makes you uncomfortable 👍

**Comment by tshaddix** [comment] 2016-10-25 15:23
@skyiea If you do end up turning your solution into a stand-alone package, I'd love to see it!

**Comment by vhmth** [comment] 2016-10-25 19:26
@skyiea this package has allowed us to scale an almost 10k LOC chrome extension to over 20,000 users. When you distribute state across multiple actors, you get into really hard-to-reason-about edge cases. This is why distributed systems as a subset of computer science is so difficult (I specialized in distributed systems for several years).

As @tshaddix said, I'd be very interested to see how your approach works if you create another module, but from a product and team scaling perspective, my experience and intuition tells me that it does not scale as well and I am not able to see a benefit of that approach given we haven't run into any real-world limitations of proxying messages to the background (even at rapid-fire).
